# Generated by Django 5.1.4 on 2024-12-17 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promgt', '0004_invoice_project_task_assignee_task_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assignee',
        ),
        migrations.AddField(
            model_name='task',
            name='assignees',
            field=models.ManyToManyField(related_name='task_assignees', to='promgt.employee'),
        ),
    ]
