# Generated by Django 5.1.4 on 2024-12-18 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promgt', '0006_alter_employee_user_alter_task_assignees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='project',
        ),
        migrations.RemoveField(
            model_name='task',
            name='assignees',
        ),
        migrations.RemoveField(
            model_name='task',
            name='project',
        ),
    ]
