# Generated by Django 5.1.4 on 2024-12-19 11:43

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promgt', '0008_project_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
